language: node_js
node_js:
  - '8'
before_script: npm install
script: npm run lint
cache:
  directories:
    - "node_modules"
deploy:
  provider: releases
  api_key:
    secure: ${API_KEY}
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true